### ISSUE TITLE
Napkin checkboxes are almost invisible

### ISSUE THREAD

**Issue by anselanza** [naivisoftware/nap_package#13]
See image below - checkboxes (bool values) have such light grey checkboxes (on white) that it is almost impossible to see what is checked or not
<img width="354" alt="Screenshot 2019-03-21 at 11 49 23" src="https://user-images.githubusercontent.com/3015222/54747549-84cf4380-4bcf-11e9-8a35-183cd091e4a3.png">

**Comment by bmod** [comment]
I've just tested all themes on Ubuntu 18.04 (Unity) and OSX Mojave (both Light and Dark), but I'm not seeing the issue: the check marks come up high contrast for me. The checkboxes in the Napkin theme should have a dark background color.

Is this on OSX Mojave with the Napkin theme? 
If so, is your desktop set to Dark or Light?
Can you make a screenshot of the entire window? 

I might have to force the color that widget in the stylesheet.

**Comment by anselanza** [comment]
This is indeed on

- MaxOS Mojave
- Napkin theme
- Dark desktop theme for MacOS
