### ISSUE TITLE
Napkin: project file dictates which modules are loaded

### ISSUE THREAD

**Issue by bmod** [naivisoftware/nap_package#21]
Not-included modules in the project file are not to be loaded.
Additionally, it would be nice if Napkin's core could be reinitialized by the user or when changing the project config.

**Comment by creywood** [comment]
Just a heads up that the first part of this should in theory be fairly easy to achieve by passing false in for the third parameter, runningInNonProjectContext, to initializeEngine.

I think it would be useful to retain this full module searching behaviour within core for possible later uses though.

**Comment by bmod** [comment]
Agreed, I was planning to keep the current behavior alongside the option to specify which modules are loaded.
