### ISSUE TITLE
Need to document built-in modules

### ISSUE THREAD

**Issue by bmod** [naivisoftware/nap_package#5]
Requested by Stephen Buchanan:

Many of the built-in features of NAP are dependent on modules, e.g. mod_naprender or mod_napmath, but in the documentation it is not clear which Classes belong to which modules.

For example, if I want to use a math::FloatFCurve* in a component I’m writing, I might go to the documentation for FCrurve (https://www.napframework.com/doxygen/d3/d76/classnap_1_1math_1_1_f_curve.html1) and there I will learn that I need to include fcurve.h but there is no mention that I will also need to modify my module dependencies to include mod_napmath. There simply is no mention of which NAP module it belongs to (at least that I can see).

**Comment by cklosters** [comment]
see: http://engine9.nl:8080/browse/NAP-276
